version: '3.4'

services:
  common-voice:
    build: .
    image: anelso42/common-voice-app
    devices:
      - /dev/input
      - /dev/snd
      - /dev/snd:/dev/snd

    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix

    ports:
      - 5000:5000
