version: '3.4'

services:
  commvoice:
    build:
      context: .
    image: anelso42/commvoice
    container_name: commvoice
    devices:
      - /dev/snd
    networks:
      - my-network
    environment:
      - ALSA_PCM=usbstream:CARD=StargazerMicrop
      - PORT=${PORT:-5000}
      - XDG_RUNTIME_DIR=/run/user/1000
      - NUMBA_CACHE_DIR=/tmp
      - ALSA_CARD=Generic
    volumes:
      - $HOME/.config/pulse:/usr/src/app/.config/pulse
      - /etc/machine-id:/etc/machine-id:ro
      - /run/user/1001/pulse:/run/user/1001/pulse:ro

    ports:
      - 5000:${PORT:-5000}

  nginx:
    build:
      context: ./commonvoice
    container_name: nginx
    depends_on:
      - commvoice
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    networks:
      my-network:
        aliases:
          - commvoice
    ports:
      - 80:80
      - 443:443
networks:
    my-network: