version: '3.7'

services:
  commvoice:
    build: .
    image: anelso42/common-voice-app
    container_name: commvoice
    devices:
      - /dev/snd
    environment:
#      - ALSA_PCM=usbstream:CARD=StargazerMicrop
      - PORT=${PORT:-8080}
      - XDG_RUNTIME_DIR=/run/user/1000
      - ALSA_CARD=Generic
    volumes:
      - $HOME/.config/pulse:/usr/src/app/.config/pulse
#      - /etc/machine-id:/etc/machine-id:ro
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
    ports:
      - 8080:${PORT:-8080}

  nginx:
    build: ./server
    container_name: nginx
    restart: always
    ports:
      - "80:80"