version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.5.4
  working_directory: ~/project


jobs:
  common-voice-model:
    docker:
      - image: circleci/python:3.5.4
    working_directory: ~/project/model
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Test Model
          command: |
            python -m venv venv
            source venv/bin/activate
            sudo pip install --upgrade pip
            pip install tox
            tox
  common-voice-api:
    docker:
      - image: circleci/python:3.5.4
    working_directory: ~/project/commonvoice
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Test API
          command: |
            python -m venv venv
            source venv/bin/activate
            sudo pip install --upgrade pip
            pip install tox
            tox

workflows:
  version: 2
  model-testing:
    jobs:
      - common-voice-model
      - common-voice-api