version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  Model Building Envnvironment:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: Install Python Model Dependencies
          command: |
            pip install --upgrade pip --user
            pip install -r model/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html --user

  Model Deployment Environment:
    docker:
      - image: circleci/python:3.8.1
    steps:
    - checkout
    - run:
        name: Install Python Deployment Dependencies
        command: |
          pip install --upgrade pip --user
          pip install -r commonvoice/requirements.txt
          pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html
          pip install commonvoice/PyAudio-0.2.11-cp38-cp38-win32.whl

workflows:
  version: 2.1
  build-env:
    jobs:
      - Model Building Envnvironment
      - Model Deployment Environment
