version: 2

defaults:
  docker:
    - image: circleci/python:3.7
  working_directory: ~/project

jobs:
  common-voice-audio_model:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/project/audio_model
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Model Unit Testing
          command: |
            sudo pip install --upgrade pip
            pip install pytest
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html
            pytest
      - run:
          names: Package Installation
          command: python setup.py sdist bdist_wheel

  common-voice-api:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/project/commonvoice
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Test API
          command: |
            python -m venv venv
            source venv/bin/activate
            sudo pip install --upgrade pip
            sudo apt-get install portaudio19-dev python-pyaudio python3-pyaudio
workflows:
  version: 2
  model-testing:
    jobs:
      - common-voice-audio_model
      - common-voice-api
