version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  Model Training:
    docker:
      - image: circleci/python:3.5.4

    steps:
      - checkout
      - run:
          name: Install Python Model Dependencies
          command: |
            pip install --upgrade pip --user
            pip install -r model/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html --user
      - run:
          name: Test LSTM Model
          command: |
            pytest model/test

      - run:
          name: build model whl
          command: |
            tox commonvoice/testenv:install_locally


  Model Deployment Environment:
    docker:
      - image: circleci/python:3.5.4
    steps:
    - checkout
    - run:
        name: Install Python Deployment Dependencies
        command: |
          pip install --upgrade pip --user
          pip install -r commonvoice/requirements.txt
          pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html
          pytest commonvoice/test

workflows:
  version: 2.1
  build-env:
    jobs:
      - Model Training
      - Model Deployment Environment
