version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.5.4

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  Model Training:
    docker:
      - image: circleci/python:3.5.4

    working_directory: ~/project/model
    steps:
      - checkout:
          - path: ~/project
      - run:
          name: Install Python Model Dependencies
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py35

  Model Deployment:
    docker:
      - image: circleci/python:3.5.4

    working_directory: ~/project/commonvoice
    steps:
      - checkout:
          - path: ~/project
      - run:
          name: Install Python Deployment Dependencies
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py35


workflows:
  version: 2.1
  build-env:
    jobs:
      - Model Training
      - Model Deployment
