version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.5.4
  working_directory: ~/project

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox
jobs:
  Model Training:
    docker:
      - image: circleci/python:3.5.4

    working_directory: ~/project/model

    steps:
      - checkout:
          - path: ~/project
      - run:
          name: Install Python Model Dependencies
          command: |
            pip install --upgrade pip --user
            pip install -U pytest
            pip install -r model/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html --user
            model/pytest

  Model Training 2:
    docker:
      - image: circleci/python:3.5.4

    working_directory: ~/project/model

    steps:
      - checkout:
          - path: ~/project
      - run:
          name: Install Python Model Dependencies
          command: |
            pip install --upgrade pip --user
            pip install -U pytest
            pip install -r model/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html --user
            pytest

  Model Deployment Environment:
    docker:
      - image: circleci/python:3.5.4
    steps:
      - checkout:
      - run:
          name: Install Python Deployment Dependencies
          command: |
            pip install --upgrade pip --user
            pip install -U pytest
            pip install -r commonvoice/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html
            pytest

  Model Deployment Environment 2:
    docker:
      - image: circleci/python:3.5.4
    steps:
      - checkout:
      - run:
          name: Install Python Deployment Dependencies
          command: |
            pip install --upgrade pip --user
            pip install -U pytest
            pip install -r commonvoice/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html
            pytest

workflows:
  version: 2.1
  build-env:
    jobs:
      - Model Training
      - Model Training 2
      - Model Deployment Environment
      - Model Deployment Environment 2