version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test_commonvoice_model:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --upgrade pip
            pip install -r model/requirements.txt
            pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html

  test_commonvoice_flask:
    docker:
      - image: circleci/python:3.7.2
    steps:
    - checkout
    - run:
        name: Test Flask Environment
        command: |
          pip install --upgrade pip
          pip install -r commonvoice/requirements.txt
          pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html
          pip install commonvoice/PyAudio-0.2.11-cp37-cp37m-win_amd64.whl

workflows:
  version: 2.1
  test-all:
    jobs:
      test_commonvoice_model
      test_commonvoice_flask
